[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::sqlalchemy.exc.LegacyAPIWarning
    ignore::jwt.warnings.InsecureKeyLengthWarning
    ignore::ResourceWarning
