from datetime import datetime

from config.database import db


class Notification(db.Model):
    """A customer-facing message generated by an event or booking change."""

    __tablename__ = "notifications"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, nullable=False, index=True)
    booking_id = db.Column(db.Integer, nullable=True, index=True)
    event_id = db.Column(db.Integer, nullable=True, index=True)
    message = db.Column(db.Text, nullable=False)
    is_read = db.Column(db.Boolean, nullable=False, default=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
